name: 'WIPAC Dev Py Dependencies'
description: 'GitHub Action Package for Automating Python-Package Dependency Management'

inputs:
  git_committer_name:
    description: 'The name used for "git config user.name"'
    required: false
    default: github-actions
  git_committer_email:
    description: 'The email used for "git config user.email"'
    required: false
    default: github-actions@github.com
  dockerfile_nametags:
    description: 'A space-separated list of image names and tags to apply to each Dockerfile for locally dependent builds (these images are built first), ex: Dockerfile:icecube/skymap_scanner:latest Dockerfile_pulsar:icecube/skymap_scanner:latest_pulsar'
    required: false
    default: ''

# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # NOTE: update, someday. Also tests.yml

    - name: Is this the most recent commit? It won't be if the action was reran
      run: |
        git fetch &> /dev/null
        if [[ $(git status -sb | grep behind) ]]; then
          echo "IS_GIT_BEHIND=true" >> $GITHUB_ENV
          echo "this commit is not the most recent on this branch -- rest of action will be skipped"
        fi
      shell: bash

    - name: Git config
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        git config user.name ${{ inputs.git_committer_name }}
        git config user.email ${{ inputs.git_committer_email }}
      shell: bash

    - name: pip
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        sudo apt-get update
        pip3 install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Build dependencies.log (and commit)
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        set -x  # turn on debugging

        # append permissive line to .gitignore since *.log is commonly present
        line='!dependencies*.log'
        if [[ ! $(grep -F "$line" .gitignore) ]]; then
          echo "" >> .gitignore
          echo "" >> .gitignore
          echo "# wipac-dev-py-setup-action" >> .gitignore
          echo "$line" >> .gitignore
          git add .gitignore
          git commit -m "<bot> update .gitignore" || true  # okay if no change
          tail .gitignore
        fi

        # remove any old ones, then regenerate only what's needed
        rm dependencies*.log || true

        export PACKAGE_NAME=$(python3 ${{ github.action_path }}/utils/get_package_name.py .)
        export GITHUB_ACTION_PATH=${{ github.action_path }}
        export ACTION_REPOSITORY="WIPACrepo/wipac-dev-py-setup-action"

        # grab local copy to avoid path mangling -- replace when https://github.com/WIPACrepo/wipac-dev-py-dependencies-action/issues/6         
        wget https://raw.githubusercontent.com/WIPACrepo/wipac-dev-tools/main/wipac_dev_tools/semver_parser_tools.py -O semver_parser_tools_local.py
        
        # get python3 version (max) -- copied from https://github.com/WIPACrepo/wipac-dev-py-versions-action/blob/main/action.yml
        export PACKAGE_MAX_PYTHON_VERSION=$(python -c '
        import os, re
        import semver_parser_tools_local as semver_parser_tools
        
        semver_range = ""
        if os.path.isfile("pyproject.toml"):
            # ex: requires-python = ">=3.8, <3.13"
            pat = re.compile(r"requires-python = \"(?P<semver_range>[^\"]+)\"$")
            with open("pyproject.toml") as f:
                for line in f:
                    if m := pat.match(line):
                        semver_range = m.group("semver_range")
            if not semver_range:
                raise Exception("could not find `requires-python` entry in pyproject.toml")
        elif os.path.isfile("setup.cfg"):
            # ex: python_requires = >=3.8, <3.13
            pat = re.compile(r"python_requires = (?P<semver_range>.+)$")
            with open("setup.cfg") as f:
                for line in f:
                    if m := pat.match(line):
                        semver_range = m.group("semver_range")
            if not semver_range:
                raise Exception("could not find `python_requires` entry in setup.cfg")
        else:
            raise Exception("could not find pyproject.toml nor setup.cfg")
        
        top_python = semver_parser_tools.get_latest_py3_release()
        all_matches = semver_parser_tools.list_all_majmin_versions(
          major=top_python[0],
          semver_range=semver_range,
          max_minor=top_python[1],
        )
        print(f"{max(all_matches)[0]}.{max(all_matches)[1]}")
        ')
        echo $PACKAGE_MAX_PYTHON_VERSION

        # Build
        if [ -f ./Dockerfile ]; then
          # from Dockerfile(s)...
          export DOCKERFILE_NAMETAGS=${{ inputs.dockerfile_nametags }}
          ${{ github.action_path }}/generate_dep_logs/gen-deps-from-repo-dockerfiles.sh
        else
          # from setup.cfg...
          ${{ github.action_path }}/generate_dep_logs/gen-deps-from-repo-python-pkg.sh
        fi

        # Commit
        git add .
        git commit -m "<bot> update dependencies*.log files(s)" || true  # okay if no change

      shell: bash

    - name: Push changes
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        status=`git status 2>&1 | tee`
        ahead=`echo -n "${status}" 2> /dev/null | grep "Your branch is ahead of" &> /dev/null; echo "$?"`
        if [ "$ahead" -eq "1" ]; then
          echo "no changes needed"
          exit 0
        fi
        git push
        echo "changes pushed"
      shell: bash
